# Generated by Django 2.2.5 on 2020-08-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
